deploy:
  provider: s3
  access_key_id: 51CJ41XWD7J4Z24HDIJH
  secret_access_key:
    secure: CuTmY4ZsESDB1+w1eU1g2PVw9Cdry2pT02bByY++jEUvQoYA6C+Wrl6P74WbB9hikeJtGI3TYXVAGkGUIUBUV/FTzujH+MeZSAKFd4qYHE09KDas/4CnkdTkV1oAeiRsqrucNVbHxw68uOKD5KPLX7wpcbGdkxGGFQqWOt9DSgW00qa+WlDbOfibvk0gpFok39NJy4qEvt42Pjh6co1a3VZoWDuWZ6Yumyr91i+c9KXbwOVsp/n2cvpiBPc7jrPLaOezayNrRZVas60/IKlLq+GH9NyGL5SgTR5gPAJQOg+B0+wN14YX8Tv9pbrKZbQWBEnXLKNpugBXSI/uQZn1VHOxPCZsQa0GwqqwrTX3eUWBGbfNOcLBf7SrUNSmnMs0yIlmNP5X0cTZ6HzHKHnjQhTNzFwXCLMNTVaQ3JRR/LwFUDEjiDo3irq+SCecNCfVUUcscQPNNEP2/doHo3LgUwF/a9fk+448dHlctamWUxHW3kNmhebTiNDNFZVmLeirgDVLSX34wBE4deXPJfV0Kvj0o1cjYdCq84csushvw0TjsubgJCrCEdLqHYSvggKQ4TTtus39XmbQGeQvROPa5dIEH6NKbyPN0xCjGV3ZquALdy7kLJcfmXsbqXgOr+xDqoTgKCZIjiv8a+fn/wIbq07B34lqj6PCpB7CxRBOFY4=
  bucket: andystevensname
  acl: public_read
  on:
    repo: andystevensname/andystevens.name
    branch: master
  endpoint: https://us-east-1.linodeobjects.com