backend:
  name: github
  repo: andystevensname/andystevens.name

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}